# Auto-generated by /Users/weisiyuan/src/edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/Users/weisiyuan/src/edk2
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/Users/weisiyuan/src/edk2/BaseTools
fi
if [ -e /Users/weisiyuan/src/edk2/BaseTools/Bin/Darwin-x86_64 ]
then
  if [ ${PATH//Users/weisiyuan/src/edk2/BaseTools/Bin/Darwin-x86_64/} == $PATH ]
  then
    export PATH=/Users/weisiyuan/src/edk2/BaseTools/Bin/Darwin-x86_64:$PATH
  fi
fi
