#define FIRMWARE_BUILDDATE "2019-08-26 22:43:12"
#define FIRMWARE_REVISION L"5057"
#define REVISION_STR "Clover revision: 5057"
#define BUILDINFOS_STR "Args: -mc --no-usb -D NO_GRUB_DRIVERS_EMBEDDED -t XCODE8 | -D DISABLE_USB_SUPPORT -D NO_GRUB_DRIVERS_EMBEDDED --conf=/Users/weisiyuan/src/edk2/Conf -D USE_BIOS_BLOCKIO -D USE_LOW_EBDA -a X64 -b RELEASE -t XCODE8 -n 5 | OS: 10.13.6 | XCODE: 10.1"
